"""
02_exploratory_analysis.py
---------------------------
Generates the exploratory + KPI visuals for the project and saves them
as PNGs in /visuals so they can be embedded directly in the README and
in reports/insights_and_recommendations.md.

Run from the repo root (after 01_data_cleaning.py):
    python python/02_exploratory_analysis.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

sns.set_theme(style="darkgrid")
plt.rcParams["figure.dpi"] = 120

DATA = Path("data/processed/supply_chain_cleaned.csv")
OUT = Path("visuals")
OUT.mkdir(exist_ok=True)

PALETTE = "viridis"


def savefig(name):
    plt.tight_layout()
    plt.savefig(OUT / name, bbox_inches="tight")
    plt.close()
    print(f"  saved visuals/{name}")


def main():
    df = pd.read_csv(DATA)
    print(f"Loaded {df.shape[0]} rows for analysis")

    # 1. Revenue by product type
    rev = df.groupby("product_type")["revenue_generated"].sum().sort_values(ascending=False)
    plt.figure(figsize=(7, 4.5))
    sns.barplot(x=rev.index, y=rev.values, hue=rev.index, palette=PALETTE, legend=False)
    plt.title("Revenue Generated by Product Type")
    plt.ylabel("Total Revenue ($)")
    plt.xlabel("Product Type")
    savefig("01_revenue_by_product_type.png")

    # 2. Revenue distribution by location
    rev_loc = df.groupby("location")["revenue_generated"].sum().sort_values(ascending=False)
    plt.figure(figsize=(6.5, 6.5))
    plt.pie(rev_loc.values, labels=rev_loc.index, autopct="%1.1f%%",
            colors=sns.color_palette(PALETTE, len(rev_loc)))
    plt.title("Revenue Distribution by Location")
    savefig("02_revenue_by_location.png")

    # 3. KPI summary bar (Order Fill Rate, On-Time Delivery, Warehouse Utilization as %;
    #    Inventory Turnover shown separately since it's not a percentage)
    ofr = df["order_fill_rate"].mean()            # row-level fill rate, capped at 100%
    otd = df["on_time_delivery_flag"].mean() * 100
    wh_util = df["warehouse_utilization_pct"].mean()
    turnover = df["inventory_turnover"].mean()

    pct_kpis = pd.Series({
        "Order Fill Rate (%)": ofr,
        "On-Time Delivery (%)": otd,
        "Warehouse Utilization (%)": wh_util,
    })
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5), gridspec_kw={"width_ratios": [2, 1]})
    sns.barplot(x=pct_kpis.index, y=pct_kpis.values, hue=pct_kpis.index,
                palette="mako", legend=False, ax=axes[0])
    axes[0].set_title("Headline KPIs (%)")
    axes[0].set_ylabel("Percent")
    axes[0].set_xlabel("")
    axes[0].set_ylim(0, 100)
    axes[0].tick_params(axis="x", rotation=15)

    axes[1].bar(["Inventory\nTurnover"], [turnover], color="#4c72b0")
    axes[1].set_title("Avg Inventory Turnover")
    axes[1].set_ylabel("Units Sold / Unit Stocked")
    savefig("03_kpi_summary.png")

    # 4. Manufacturing cost vs price by product type
    price_cost = df.groupby("product_type").agg(
        Price=("price", "sum"), Manufacturing_Cost=("manufacturing_costs", "sum")
    ).reset_index()
    price_cost_m = price_cost.melt(id_vars="product_type", var_name="Metric", value_name="Value")
    plt.figure(figsize=(7.5, 4.5))
    sns.barplot(data=price_cost_m, x="product_type", y="Value", hue="Metric", palette="Set2")
    plt.title("Price vs. Manufacturing Cost by Product Type")
    plt.ylabel("$ (summed across SKUs)")
    plt.xlabel("Product Type")
    savefig("04_price_vs_manufacturing_cost.png")

    # 5. Profitability by product type
    profit = df.groupby("product_type")["profit"].sum().sort_values()
    plt.figure(figsize=(7, 4.5))
    colors = ["#d62728" if v < 0 else "#2ca02c" for v in profit.values]
    plt.barh(profit.index, profit.values, color=colors)
    plt.title("Overall Profitability by Product Type")
    plt.xlabel("Profit ($)")
    savefig("05_profitability_by_product_type.png")

    # 6. Defect rate by inspection result
    plt.figure(figsize=(6.5, 4.5))
    sns.boxplot(data=df, x="inspection_results", y="defect_rates", hue="inspection_results",
                palette="coolwarm", legend=False)
    plt.title("Defect Rates by Inspection Result")
    plt.xlabel("Inspection Result")
    plt.ylabel("Defect Rate (%)")
    savefig("06_defect_rates_by_inspection.png")

    # 7. Transportation mode frequency + cost
    mode_summary = df.groupby("transportation_modes").agg(
        avg_shipping_cost=("shipping_costs", "mean"),
        avg_shipping_time=("shipping_times", "mean"),
        n=("record_id", "count"),
    ).reset_index()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))
    sns.barplot(data=mode_summary, x="transportation_modes", y="n", hue="transportation_modes",
                palette="crest", legend=False, ax=axes[0])
    axes[0].set_title("Shipment Count by Transportation Mode")
    axes[0].set_ylabel("Count")
    axes[0].set_xlabel("")
    sns.scatterplot(data=mode_summary, x="avg_shipping_time", y="avg_shipping_cost",
                     hue="transportation_modes", s=180, palette="crest", ax=axes[1])
    axes[1].set_title("Avg Shipping Time vs. Cost by Mode")
    axes[1].set_xlabel("Avg Shipping Time (days)")
    axes[1].set_ylabel("Avg Shipping Cost ($)")
    savefig("07_transportation_mode_analysis.png")

    # 8. Supplier defect / lead time performance
    supplier_perf = df.groupby("supplier_name").agg(
        avg_defect_rate=("defect_rates", "mean"), avg_lead_time=("lead_times", "mean")
    ).reset_index()
    plt.figure(figsize=(7, 5))
    sns.scatterplot(data=supplier_perf, x="avg_lead_time", y="avg_defect_rate",
                     hue="supplier_name", s=160, palette="tab10")
    plt.title("Supplier Performance: Lead Time vs. Defect Rate")
    plt.xlabel("Avg Lead Time (days)")
    plt.ylabel("Avg Defect Rate (%)")
    plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8)
    savefig("08_supplier_performance.png")

    # 9. Warehouse utilization by location
    wh = df.groupby("location")["warehouse_utilization_pct"].mean().sort_values(ascending=False)
    plt.figure(figsize=(7, 4.5))
    sns.barplot(x=wh.index, y=wh.values, hue=wh.index, palette="flare", legend=False)
    plt.title("Average Warehouse Utilization by Location")
    plt.ylabel("Warehouse Utilization (%)")
    plt.xlabel("Location")
    savefig("09_warehouse_utilization_by_location.png")

    # 10. Correlation heatmap of core numeric KPIs
    numeric_cols = [
        "price", "availability", "number_of_products_sold", "revenue_generated",
        "stock_levels", "lead_times", "order_quantities", "shipping_times",
        "shipping_costs", "manufacturing_costs", "defect_rates", "costs", "profit",
    ]
    corr = df[numeric_cols].corr()
    plt.figure(figsize=(10, 8))
    sns.heatmap(corr, cmap="RdBu_r", center=0, annot=False, square=True)
    plt.title("Correlation Heatmap: Core Supply Chain Metrics")
    savefig("10_correlation_heatmap.png")

    print("\nAll visuals generated in /visuals")


if __name__ == "__main__":
    main()
